-- Police FIR System - Catalyst Data Store Schema
-- Based on Police_FIR_ER_Diagram.pdf.
-- CSV seed files are generated by scripts/generate_fir_er_data.py.

CREATE TABLE IF NOT EXISTS State (
    StateID INT PRIMARY KEY,
    StateName VARCHAR(100),
    NationalityID INT,
    Active BIT
);

CREATE TABLE IF NOT EXISTS District (
    DistrictID INT PRIMARY KEY,
    DistrictName VARCHAR(100),
    StateID INT,
    Active BIT
);

CREATE TABLE IF NOT EXISTS UnitType (
    UnitTypeID INT PRIMARY KEY,
    UnitTypeName VARCHAR(100),
    CityDistState VARCHAR(50),
    Hierarchy INT,
    Active BIT
);

CREATE TABLE IF NOT EXISTS Unit (
    UnitID INT PRIMARY KEY,
    UnitName VARCHAR(150),
    TypeID INT,
    ParentUnit INT,
    NationalityID INT,
    StateID INT,
    DistrictID INT,
    Active BIT
);

CREATE TABLE IF NOT EXISTS Rank (
    RankID INT PRIMARY KEY,
    RankName VARCHAR(100),
    Hierarchy INT,
    Active BIT
);

CREATE TABLE IF NOT EXISTS Designation (
    DesignationID INT PRIMARY KEY,
    DesignationName VARCHAR(120),
    Active BIT,
    SortOrder INT
);

CREATE TABLE IF NOT EXISTS Employee (
    EmployeeID INT PRIMARY KEY,
    DistrictID INT,
    UnitID INT,
    RankID INT,
    DesignationID INT,
    KGID VARCHAR(40),
    FirstName VARCHAR(80),
    EmployeeDOB DATE,
    GenderID INT,
    BloodGroupID INT,
    PhysicallyChallenged BIT,
    AppointmentDate DATE
);

CREATE TABLE IF NOT EXISTS Court (
    CourtID INT PRIMARY KEY,
    CourtName VARCHAR(150),
    DistrictID INT,
    StateID INT,
    Active BIT
);

CREATE TABLE IF NOT EXISTS CaseCategory (
    CaseCategoryID INT PRIMARY KEY,
    LookupValue VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS GravityOffence (
    GravityOffenceID INT PRIMARY KEY,
    LookupValue VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS CaseStatusMaster (
    CaseStatusID INT PRIMARY KEY,
    CaseStatusName VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS OccupationMaster (
    OccupationID INT PRIMARY KEY,
    OccupationName VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ReligionMaster (
    ReligionID INT PRIMARY KEY,
    ReligionName VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CasteMaster (
    caste_master_id INT PRIMARY KEY,
    caste_master_name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CrimeHead (
    CrimeHeadID INT PRIMARY KEY,
    CrimeGroupName VARCHAR(120),
    Active BIT
);

CREATE TABLE IF NOT EXISTS CrimeSubHead (
    CrimeSubHeadID INT PRIMARY KEY,
    CrimeHeadID INT,
    CrimeHeadName VARCHAR(120),
    SeqID INT
);

CREATE TABLE IF NOT EXISTS Act (
    ActCode VARCHAR(40) PRIMARY KEY,
    ActDescription VARCHAR(255),
    ShortName VARCHAR(80),
    Active BIT
);

CREATE TABLE IF NOT EXISTS Section (
    ActCode VARCHAR(40),
    SectionCode VARCHAR(40),
    SectionDescription VARCHAR(255),
    Active BIT
);

CREATE TABLE IF NOT EXISTS CrimeHeadActSection (
    CrimeHeadID INT,
    ActCode VARCHAR(40),
    SectionCode VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS CaseMaster (
    CaseMasterID INT PRIMARY KEY,
    CrimeNo VARCHAR(40),
    CaseNo VARCHAR(20),
    CrimeRegisteredDate DATE,
    PolicePersonID INT,
    PoliceStationID INT,
    CaseCategoryID INT,
    GravityOffenceID INT,
    CrimeMajorHeadID INT,
    CrimeMinorHeadID INT,
    CaseStatusID INT,
    CourtID INT,
    IncidentFromDate DATETIME,
    IncidentToDate DATETIME,
    InfoReceivedPSDate DATETIME,
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6),
    BriefFacts TEXT
);

CREATE TABLE IF NOT EXISTS ComplainantDetails (
    ComplainantID INT PRIMARY KEY,
    CaseMasterID INT,
    ComplainantName VARCHAR(120),
    AgeYear INT,
    OccupationID INT,
    ReligionID INT,
    CasteID INT,
    GenderID INT
);

CREATE TABLE IF NOT EXISTS Victim (
    VictimMasterID INT PRIMARY KEY,
    CaseMasterID INT,
    VictimName VARCHAR(120),
    AgeYear INT,
    GenderID INT,
    VictimPolice BIT
);

CREATE TABLE IF NOT EXISTS Accused (
    AccusedMasterID INT PRIMARY KEY,
    CaseMasterID INT,
    AccusedName VARCHAR(120),
    AgeYear INT,
    GenderID INT,
    PersonID VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS ActSectionAssociation (
    CaseMasterID INT,
    ActID VARCHAR(40),
    SectionID VARCHAR(40),
    ActOrderID INT,
    SectionOrderID INT
);

CREATE TABLE IF NOT EXISTS Inv_OccuranceTime (
    OccuranceTimeID INT PRIMARY KEY,
    CaseMasterID INT,
    FromDate DATETIME,
    ToDate DATETIME,
    PlaceOfOccurance VARCHAR(120),
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6)
);

CREATE TABLE IF NOT EXISTS ArrestSurrender (
    ArrestSurrenderID INT PRIMARY KEY,
    CaseMasterID INT,
    ArrestSurrenderTypeID INT,
    ArrestSurrenderDate DATE,
    ArrestSurrenderStateId INT,
    ArrestSurrenderDistrictId INT,
    PoliceStationID INT,
    IOID INT,
    CourtID INT,
    AccusedMasterID INT,
    IsAccused BIT,
    IsComplainantAccused BIT
);

CREATE TABLE IF NOT EXISTS inv_arrestsurrenderaccused (
    ArrestSurrenderAccusedID INT PRIMARY KEY,
    ArrestSurrenderID INT,
    AccusedMasterID INT
);

CREATE TABLE IF NOT EXISTS ChargesheetDetails (
    CSID INT PRIMARY KEY,
    CaseMasterID INT,
    csdate DATETIME,
    cstype CHAR(1),
    PolicePersonID INT
);
